package riverdalerobotics;

public class EmmaGui extends javax.swing.JFrame 
{

    // Emma GUI singleton
    static public EmmaGui m_emmaGui;
    /**
     * Creates new form EmmaGui
     */
    public EmmaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_modeGroup = new javax.swing.ButtonGroup();
        m_rightJoystickXSlider = new javax.swing.JSlider();
        m_leftJoystickXLabel = new javax.swing.JLabel();
        m_leftJoystickYLabel = new javax.swing.JLabel();
        m_leftJoystickYSlider = new javax.swing.JSlider();
        m_rightJoystickYSlider = new javax.swing.JSlider();
        m_rightJoystickYLabel = new javax.swing.JLabel();
        m_leftJoystickXSlider = new javax.swing.JSlider();
        m_rightJoystickLabel = new javax.swing.JLabel();
        m_leftJoystickButtonsLabel = new javax.swing.JLabel();
        m_leftJoystickButton1 = new javax.swing.JToggleButton();
        m_leftJoystickButton2 = new javax.swing.JToggleButton();
        m_leftJoystickButton3 = new javax.swing.JToggleButton();
        m_leftJoystickButton4 = new javax.swing.JToggleButton();
        m_rightJoystickButton3 = new javax.swing.JToggleButton();
        m_rightJoystickButton4 = new javax.swing.JToggleButton();
        m_rightJoystickButton1 = new javax.swing.JToggleButton();
        m_rightJoystickButton2 = new javax.swing.JToggleButton();
        m_rightJoystickButtonsLabel = new javax.swing.JLabel();
        m_leftWheelJagLabel = new javax.swing.JLabel();
        m_leftWheelJagText = new javax.swing.JTextField();
        m_rightWheelJagLabel = new javax.swing.JLabel();
        m_rightWheelJagText = new javax.swing.JTextField();
        m_rightLiftJagLabel = new javax.swing.JLabel();
        m_rightLiftJagText = new javax.swing.JTextField();
        m_leftLiftJagLabel = new javax.swing.JLabel();
        m_leftLiftJagText = new javax.swing.JTextField();
        m_disabledModeRadio = new javax.swing.JRadioButton();
        m_autonomousModeRadio = new javax.swing.JRadioButton();
        m_teleopModeRadio = new javax.swing.JRadioButton();
        m_feedbackText = new javax.swing.JTextField();
        m_shootRotaryJagText = new javax.swing.JTextField();
        m_shootHopperJagLabel = new javax.swing.JLabel();
        m_shootHopperJagText = new javax.swing.JTextField();
        m_shootRotaryJagLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emma - Riverdale Robotics Emulator");

        m_leftJoystickXLabel.setText("Left Joystick X");

        m_leftJoystickYLabel.setText("Left Joystick Y");

        m_rightJoystickYLabel.setText("Right Joystick Y");

        m_rightJoystickLabel.setText("Right Joystick X");

        m_leftJoystickButtonsLabel.setText("Left Joystick Buttons");

        m_leftJoystickButton1.setText("1");
        m_leftJoystickButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leftJoystickButton1ActionPerformed(evt);
            }
        });

        m_leftJoystickButton2.setText("2");
        m_leftJoystickButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leftJoystickButton2ActionPerformed(evt);
            }
        });

        m_leftJoystickButton3.setText("3");
        m_leftJoystickButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leftJoystickButton3ActionPerformed(evt);
            }
        });

        m_leftJoystickButton4.setText("4");
        m_leftJoystickButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leftJoystickButton4ActionPerformed(evt);
            }
        });

        m_rightJoystickButton3.setText("3");
        m_rightJoystickButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_rightJoystickButton3ActionPerformed(evt);
            }
        });

        m_rightJoystickButton4.setText("4");
        m_rightJoystickButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_rightJoystickButton4ActionPerformed(evt);
            }
        });

        m_rightJoystickButton1.setText("1");
        m_rightJoystickButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_rightJoystickButton1ActionPerformed(evt);
            }
        });

        m_rightJoystickButton2.setText("2");
        m_rightJoystickButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_rightJoystickButton2ActionPerformed(evt);
            }
        });

        m_rightJoystickButtonsLabel.setText("Right Joystick Buttons");

        m_leftWheelJagLabel.setLabelFor(this);
        m_leftWheelJagLabel.setText("Left Wheel Jag");

        m_leftWheelJagText.setText("jTextField1");

        m_rightWheelJagLabel.setText("Right Wheel Jag");
        m_rightWheelJagLabel.setToolTipText("");

        m_rightWheelJagText.setText("jTextField1");

        m_rightLiftJagLabel.setText("Right Lift Jag");

        m_rightLiftJagText.setText("jTextField1");

        m_leftLiftJagLabel.setText("Left Lift Jag");

        m_leftLiftJagText.setText("jTextField1");
        m_leftLiftJagText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_leftLiftJagTextActionPerformed(evt);
            }
        });

        m_modeGroup.add(m_disabledModeRadio);
        m_disabledModeRadio.setSelected(true);
        m_disabledModeRadio.setText("Disabled");

        m_modeGroup.add(m_autonomousModeRadio);
        m_autonomousModeRadio.setText("Autonomous");

        m_modeGroup.add(m_teleopModeRadio);
        m_teleopModeRadio.setText("Teleop");

        m_feedbackText.setText("jTextField1");

        m_shootRotaryJagText.setText("jTextField1");

        m_shootHopperJagLabel.setText("Shoot Hopper Jag");

        m_shootHopperJagText.setText("jTextField1");

        m_shootRotaryJagLabel.setText("Shoot Rotary Jag");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(m_disabledModeRadio)
                .addGap(10, 10, 10)
                .addComponent(m_autonomousModeRadio)
                .addGap(10, 10, 10)
                .addComponent(m_teleopModeRadio)
                .addGap(18, 18, 18)
                .addComponent(m_feedbackText, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(m_shootRotaryJagLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_shootRotaryJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m_leftJoystickYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m_leftJoystickYSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m_leftJoystickXLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m_leftJoystickXSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(m_leftJoystickButtonsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m_leftJoystickButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m_leftJoystickButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m_leftJoystickButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m_leftJoystickButton4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m_leftLiftJagLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(m_leftLiftJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m_leftWheelJagLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(m_leftWheelJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_rightJoystickXSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(m_rightJoystickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(m_rightJoystickYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(m_rightJoystickButtonsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m_rightJoystickButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m_rightJoystickButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m_rightJoystickButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m_rightJoystickButton4))
                            .addComponent(m_rightJoystickYSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m_rightLiftJagLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(m_rightLiftJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m_rightWheelJagLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(m_rightWheelJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m_shootHopperJagLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m_shootHopperJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_autonomousModeRadio)
                    .addComponent(m_teleopModeRadio)
                    .addComponent(m_disabledModeRadio)
                    .addComponent(m_feedbackText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_leftJoystickXLabel)
                    .addComponent(m_rightJoystickLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_rightJoystickXSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_leftJoystickXSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_rightJoystickYLabel)
                            .addComponent(m_leftJoystickYLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_leftJoystickYSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m_rightJoystickYSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(m_rightJoystickButtonsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_rightJoystickButton1)
                            .addComponent(m_rightJoystickButton2)
                            .addComponent(m_rightJoystickButton3)
                            .addComponent(m_rightJoystickButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m_leftJoystickButtonsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m_leftJoystickButton1)
                            .addComponent(m_leftJoystickButton2)
                            .addComponent(m_leftJoystickButton3)
                            .addComponent(m_leftJoystickButton4))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_leftWheelJagLabel)
                    .addComponent(m_leftWheelJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_rightWheelJagLabel)
                    .addComponent(m_rightWheelJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_leftLiftJagLabel)
                    .addComponent(m_leftLiftJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_rightLiftJagLabel)
                    .addComponent(m_rightLiftJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_shootRotaryJagLabel)
                    .addComponent(m_shootHopperJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_shootHopperJagLabel)
                    .addComponent(m_shootRotaryJagText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_leftJoystickButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_leftJoystickButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leftJoystickButton1ActionPerformed

    private void m_leftJoystickButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_leftJoystickButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leftJoystickButton2ActionPerformed

    private void m_leftJoystickButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_leftJoystickButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leftJoystickButton3ActionPerformed

    private void m_leftJoystickButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_leftJoystickButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leftJoystickButton4ActionPerformed

    private void m_rightJoystickButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_rightJoystickButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_rightJoystickButton3ActionPerformed

    private void m_rightJoystickButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_rightJoystickButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_rightJoystickButton4ActionPerformed

    private void m_rightJoystickButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_rightJoystickButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_rightJoystickButton1ActionPerformed

    private void m_rightJoystickButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_rightJoystickButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_rightJoystickButton2ActionPerformed

    private void m_leftLiftJagTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_m_leftLiftJagTextActionPerformed
    {//GEN-HEADEREND:event_m_leftLiftJagTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_leftLiftJagTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmmaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmmaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmmaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmmaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                // Create the GUI
                m_emmaGui = new EmmaGui();
                m_emmaGui.setVisible(true);
                // create the robot thread
                PandaBot robot = new PandaBot();
                (new Thread(robot)).start();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton m_autonomousModeRadio;
    private javax.swing.JRadioButton m_disabledModeRadio;
    private javax.swing.JTextField m_feedbackText;
    private javax.swing.JToggleButton m_leftJoystickButton1;
    private javax.swing.JToggleButton m_leftJoystickButton2;
    private javax.swing.JToggleButton m_leftJoystickButton3;
    private javax.swing.JToggleButton m_leftJoystickButton4;
    private javax.swing.JLabel m_leftJoystickButtonsLabel;
    private javax.swing.JLabel m_leftJoystickXLabel;
    private javax.swing.JSlider m_leftJoystickXSlider;
    private javax.swing.JLabel m_leftJoystickYLabel;
    private javax.swing.JSlider m_leftJoystickYSlider;
    private javax.swing.JLabel m_leftLiftJagLabel;
    private javax.swing.JTextField m_leftLiftJagText;
    private javax.swing.JLabel m_leftWheelJagLabel;
    private javax.swing.JTextField m_leftWheelJagText;
    private javax.swing.ButtonGroup m_modeGroup;
    private javax.swing.JToggleButton m_rightJoystickButton1;
    private javax.swing.JToggleButton m_rightJoystickButton2;
    private javax.swing.JToggleButton m_rightJoystickButton3;
    private javax.swing.JToggleButton m_rightJoystickButton4;
    private javax.swing.JLabel m_rightJoystickButtonsLabel;
    private javax.swing.JLabel m_rightJoystickLabel;
    private javax.swing.JSlider m_rightJoystickXSlider;
    private javax.swing.JLabel m_rightJoystickYLabel;
    private javax.swing.JSlider m_rightJoystickYSlider;
    private javax.swing.JLabel m_rightLiftJagLabel;
    private javax.swing.JTextField m_rightLiftJagText;
    private javax.swing.JLabel m_rightWheelJagLabel;
    private javax.swing.JTextField m_rightWheelJagText;
    private javax.swing.JLabel m_shootHopperJagLabel;
    private javax.swing.JTextField m_shootHopperJagText;
    private javax.swing.JLabel m_shootRotaryJagLabel;
    private javax.swing.JTextField m_shootRotaryJagText;
    private javax.swing.JRadioButton m_teleopModeRadio;
    // End of variables declaration//GEN-END:variables

    
    public boolean getDisabled()
    {
        return m_disabledModeRadio.isSelected();
    }

    public boolean getAutonomous()
    {
        return m_autonomousModeRadio.isSelected();
    }

    public boolean getOperatorControl()
    {
        return m_teleopModeRadio.isSelected();
    }
    
    public void setFeedback(String feedback)
    {
        m_feedbackText.setText(feedback);
    }
    
    public javax.swing.JSlider getXSlider(int port)
    {
        return port == 1 ? m_leftJoystickXSlider : m_rightJoystickXSlider;
    }

    public javax.swing.JSlider getYSlider(int port)
    {
        return port == 1 ? m_leftJoystickYSlider : m_rightJoystickYSlider;
    }
    
    public javax.swing.JToggleButton[] getButtons(int port)
    {
        javax.swing.JToggleButton buttons[] = new javax.swing.JToggleButton[4];
        if (port == 1)
        {
            buttons[0] = m_leftJoystickButton1;
            buttons[1] = m_leftJoystickButton2;
            buttons[2] = m_leftJoystickButton3;
            buttons[3] = m_leftJoystickButton4;
        }
        else if (port == 2)
        {
            buttons[0] = m_leftJoystickButton1;
            buttons[1] = m_leftJoystickButton2;
            buttons[2] = m_leftJoystickButton3;
            buttons[3] = m_leftJoystickButton4;
        }
        return buttons;   
    }
    
    javax.swing.JTextField getJaguar(final int channel)
    {
        if (channel == 2)
        {
            return m_leftWheelJagText;
        }
        else if (channel == 6)
        {
            return m_rightWheelJagText;
        }
        else if (channel == 1)
        {
            return m_leftLiftJagText;
        }
        else if (channel == 1)
        {
            return m_rightLiftJagText;
        }
        else if (channel == 8)
        {
            return m_shootRotaryJagText;
        }
        else if (channel == 10)
        {
            return m_shootHopperJagText;
        }
        return null;
    }

}
